Repository necst-telescope/necst, pull requests merged in 2022-11, with the labels that each got.

#88 Reflect quick fixes done in trip
  necst/core/__init__.py
  necst/core/device_node.py
  necst/ctrl/antenna/encoder.py
  necst/ctrl/antenna/motor.py
  necst/ctrl/antenna/thermometer_reader.py
Labels: bug

#89 Avoid deadlock after ping attempt
  necst/core/authorizer.py
  necst/core/privileged_node.py
  tests/core/test_authority.py
Labels: bug

#91 Use context manager to change PID configurations
  docs/index.md
  necst/ctrl/antenna/pid_controller.py
Labels: enhancement

#94 Add QoS policy detector
  necst/__init__.py
  necst/core/recorder.py
  tests/test_qos.py
Labels: enhancement, invalid

#95 #84 add weather status change
  necst/ctrl/antenna/horizontal_coord.py
Labels: enhancement

#97 #93-change namespace from antenna to ctrl
  necst/ctrl/antenna/horizontal_coord.py
  necst/ctrl/antenna/thermometer_reader.py
Labels: invalid

#99 Release v0.3.1
  .github/ISSUE_TEMPLATE/release.md
  package.xml
  setup.py
Labels: release

#100 #49 alert
  .devcontainer/devcontainer.json
  docs/conf.py
  necst/__init__.py
  necst/core/__init__.py
  necst/core/alert/__init__.py
  necst/core/alert/alert_handler_node.py
  necst/core/alert/antenna_drive_range.py
  necst/core/alert/antenna_speed.py
  necst/core/auth/__init__.py
  necst/core/auth/authorizer.py
  necst/core/auth/privileged_node.py
  necst/core/commander.py
  necst/core/exec_alert.py
  necst/core/recorder.py
  necst/ctrl/antenna/horizontal_coord.py
  necst/ctrl/antenna/motor.py
  necst/ctrl/antenna/pid_controller.py
  necst/tester.py
  necst/utils/__init__.py
  necst/utils/ros_interface.py
  necst/utils/ros_thread.py
  tests/conftest.py
  tests/core/alert/__init__.py
  tests/core/alert/test_alert_handler_node.py
  tests/core/alert/test_antenna_drive_range.py
  tests/core/alert/test_antenna_speed.py
  tests/core/test_authority.py
  tests/core/test_commander.py
  tests/core/test_recorder.py
  tests/ctrl/test_antenna_controller.py
  tests/ctrl/test_coordinate_conversion.py
  tests/ctrl/test_sim_devices.py
  tests/integration/test_antenna.py
Labels: enhancement

#103 Define topic and service configurations
  .github/workflows/test.yml
  necst/__init__.py
  necst/core/alert/antenna_drive_range.py
  necst/core/alert/antenna_speed.py
  necst/core/auth/authorizer.py
  necst/core/auth/privileged_node.py
  necst/core/commander.py
  necst/core/device_node.py
  necst/core/recorder.py
  necst/ctrl/antenna/encoder.py
  necst/ctrl/antenna/horizontal_coord.py
  necst/ctrl/antenna/motor.py
  necst/ctrl/antenna/pid_controller.py
  necst/ctrl/antenna/sim_devices.py
  necst/ctrl/antenna/thermometer_reader.py
  necst/definitions.py
  necst/utils/ros_interface.py
  tests/conftest.py
  tests/core/test_authority.py
  tests/core/test_commander.py
Labels: enhancement

#105 Support changing PID parameters from `Commander`
  necst/core/commander.py
  necst/ctrl/antenna/pid_controller.py
  necst/definitions.py
  necst/utils/ros_interface.py
  tests/core/test_commander.py
  tests/ctrl/test_antenna_controller.py
  tests/integration/__init__.py
  tests/integration/test_antenna.py
Labels: enhancement
