Repository necst-telescope/necst, pull requests merged in 2022-09, with the labels that each got.

#21 Fix documentation building workflow
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/actions/setup-necst/action.yml
  .github/workflows/gh-pages.yml
  .github/workflows/test.yml
  setup.py
  tests/docs/test_build.py
Labels: documentation, enhancement

#27 Fix workflow trigger
  .github/workflows/gh-pages.yml
  tests/conftest.py
  tests/test_nothing.py
Labels: enhancement

#25 Implement system controller
  necst/core/__init__.py
  necst/core/commander.py
  tests/conftest.py
  tests/core/__init__.py
  tests/core/test_commander.py
Labels: enhancement

#30 Implement antenna motion simulator
  necst/ctrl/antenna_simulater.py
Labels: enhancement

#32 Integration testing for antenna control
  .devcontainer/devcontainer.json
  Dockerfile
  necst/__init__.py
  necst/core/commander.py
  necst/ctrl/antenna/__init__.py
  necst/ctrl/antenna/coordinate_conversion.py
  necst/ctrl/antenna/driver.py
  necst/ctrl/antenna/pid_controller.py
  necst/ctrl/calculations/__init__.py
  necst/ctrl/exec_antenna.py
  necst/tempos/__init__.py
  necst/tempos/ros2_string_pub.py
  necst/tempos/subscriber_member_function.py
  setup.py
  tests/conftest.py
  tests/core/test_commander.py
  tests/ctrl/test_antenna_controller.py
  tests/ctrl/test_coordinate_conversion.py
  tests/integration/__init__.py
  tests/integration/test_antenna.py
  tests/test_ros2_string_pub.py
Labels: enhancement

#36 Track the target
  .devcontainer/Dockerfile
  necst/__init__.py
  necst/core/__init__.py
  necst/core/commander.py
  necst/core/exec_record.py
  necst/core/recorder.py
  necst/ctrl/antenna/__init__.py
  necst/ctrl/antenna/coordinate_conversion.py
  necst/ctrl/antenna/encoder.py
  necst/ctrl/antenna/horizontal_coord.py
  necst/ctrl/antenna/motor.py
  necst/ctrl/antenna/pid_controller.py
  necst/ctrl/antenna/sim_devices.py
  necst/ctrl/exec_antenna_cal.py
  necst/ctrl/exec_antenna_dev.py
  necst/ctrl/exec_antenna_sim.py
  package.xml
  setup.py
  tests/core/test_commander.py
  tests/ctrl/test_antenna_controller.py
  tests/ctrl/test_coordinate_conversion.py
  tests/integration/test_antenna.py
Labels: bug, enhancement

#38 Update project version
  package.xml
  setup.py
Labels: release

#40 Fix environment to run NECST
  Dockerfile
Labels: bug

#41 Version 0.2.2
  package.xml
  setup.py
Labels: bug

#44 Resolve bugs identified during in-situ testing
  necst/ctrl/antenna/motor.py
Labels: bug

#47 Support real-time control of motor controller
  necst/ctrl/antenna/motor.py
Labels: invalid

#48 Add installation of pciutils
  Dockerfile
Labels: bug

#17 Implement privilege handler
  necst/__init__.py
  necst/core/__init__.py
  necst/core/authorizer.py
  necst/core/privileged_node.py
  necst/tester.py
  necst/utils/__init__.py
  necst/utils/callbacks.py
  necst/utils/ros_interface.py
  tests/conftest.py
  tests/core/test_authority.py
Labels: enhancement

#52 Add code coverage report
  .devcontainer/Dockerfile
  .github/workflows/test.yml
  README.md
  tests/docs/test_build.py
  tests/integration/test_antenna.py
Labels: documentation, enhancement

#53 Fix command to dump coverage report
  .github/workflows/test.yml
Labels: bug, enhancement

#55 #50 recorder
  .devcontainer/Dockerfile
  necst/core/recorder.py
  tests/core/test_recorder.py
Labels: bug

#57 Use privilege handler in commander
  docs/conf.py
  necst/core/authorizer.py
  necst/core/commander.py
  necst/core/privileged_node.py
  necst/ctrl/antenna/horizontal_coord.py
  tests/core/test_commander.py
  tests/ctrl/test_coordinate_conversion.py
  tests/docs/test_build.py
  tests/integration/test_antenna.py
Labels: invalid
