Repository necst-telescope/necst, pull requests merged in 2022-10, with the labels that each got.

#54 add test_sim_devices.py
  necst/ctrl/antenna/sim_devices.py
  tests/ctrl/test_sim_devices.py
Labels: enhancement

#66 change DBWriter to Recorder
  necst/core/recorder.py
  necst/ctrl/antenna/horizontal_coord.py
  tests/core/test_recorder.py
Labels: bug

#58 #29 pid制御
  necst/ctrl/antenna/pid_controller.py
  tests/ctrl/test_antenna_controller.py
Labels: enhancement

#67 add thermometer_reader
  necst/ctrl/antenna/__init__.py
  necst/ctrl/antenna/thermometer_reader.py
Labels: enhancement

#70 Use config values for PID controller
  necst/ctrl/antenna/pid_controller.py
Labels: bug

#71 Reflect change of device controller naming convention
  necst/ctrl/antenna/encoder.py
  necst/ctrl/antenna/motor.py
Labels: bug

#74 add ThermometerReader in exec_antenna_dev
  necst/ctrl/exec_antenna_dev.py
Labels: enhancement

#79 Use deceleration calculator
  necst/ctrl/antenna/pid_controller.py
Labels: enhancement, invalid

#81 Fix function usage
  necst/ctrl/antenna/thermometer_reader.py
Labels: bug

#83 Fix dropped command handling
  necst/ctrl/antenna/pid_controller.py
  necst/ctrl/exec_antenna_dev.py
Labels: bug
