Repository necst-telescope/necst, pull requests merged in 2022-12, with the labels that each got.

#109 Add chopper controller
  .devcontainer/devcontainer.json
  Dockerfile
  necst/core/auth/authorizer.py
  necst/core/auth/privileged_node.py
  necst/core/commander.py
  necst/core/server_node.py
  necst/ctrl/calibrator/__init__.py
  necst/ctrl/calibrator/chopper.py
  necst/definitions.py
  necst/utils/ros_thread.py
  tests/conftest.py
  tests/core/test_authority.py
  tests/core/test_commander.py
Labels: enhancement

#111 Fix type hints in `Commander` method definitions
  necst/core/commander.py
  typings/necst_msgs/__init__.pyi
  typings/necst_msgs/msg/__init__.pyi
  typings/necst_msgs/srv/__init__.pyi
Labels: bug

#114 Fix server node usage
  necst/core/exec_auth.py
  tests/core/test_authority.py
  typings/necst_msgs/msg/__init__.pyi
  typings/necst_msgs/srv/__init__.pyi
Labels: bug

#118 Change RMW implementation in devcontainer
  .devcontainer/Dockerfile
  Dockerfile
Labels: bug

#120 Release v0.3.2
  package.xml
  setup.py
Labels: release

#116 Convert quantity data to float
  necst/ctrl/antenna/motor.py
Labels: bug

#122 #121 change altaz_cmd
  necst/definitions.py
  obs/rsky_obs.py
  obs/skydip_obs.py
  tests/core/test_commander.py
  tests/ctrl/test_antenna_controller.py
  tests/obs/__init__.py
  tests/obs/test_rsky_obs.py
  tests/obs/test_skydip_obs.py
Labels: bug

#106 #85 Implement scan command
  necst/core/commander.py
  necst/ctrl/antenna/horizontal_coord.py
  necst/definitions.py
  tests/core/test_commander.py
  tests/ctrl/test_coordinate_conversion.py
Labels: enhancement

#125 Fix real-time command selection
  necst/ctrl/antenna/pid_controller.py
  necst/definitions.py
  tests/core/test_commander.py
Labels: bug

#135 #127 Fix typo and enable to use `"scan"` command
  necst/core/commander.py
Labels: bug

#132 Fix convergence check timing
  necst/core/alert/alert_handler_node.py
  necst/core/commander.py
  necst/definitions.py
  tests/core/test_commander.py
Labels: bug

#134 #123 Fix msg string length if specified
  necst/core/recorder.py
Labels: enhancement

#133 Fix procedure on communication loss with encoder
  necst/ctrl/antenna/horizontal_coord.py
  tests/ctrl/test_coordinate_conversion.py
Labels: bug

#139 Fix data type parsing
  necst/core/recorder.py
Labels: bug

#131 Fix controller setting
  necst/core/commander.py
  necst/core/recorder.py
  necst/ctrl/antenna/horizontal_coord.py
  necst/ctrl/antenna/pid_controller.py
Labels: bug

#144 Support generator type coordinate calculation result
  Dockerfile
  README.md
  necst/__init__.py
  necst/core/commander.py
  necst/core/recorder.py
  necst/ctrl/antenna/horizontal_coord.py
  necst/ctrl/antenna/motor.py
  necst/ctrl/antenna/pid_controller.py
  necst/definitions.py
  necst/rx/spectrometer.py
  tests/ctrl/test_antenna_controller.py
Labels: enhancement

#146 Use dedicated message type for weather information
  necst/ctrl/antenna/horizontal_coord.py
  necst/ctrl/antenna/weather_station.py
  necst/definitions.py
Labels: enhancement, invalid

#147 Add receiver device controllers
  .devcontainer/Dockerfile
  Dockerfile
  README.md
  necst/core/__init__.py
  necst/core/clock.py
  necst/core/commander.py
  necst/core/recorder.py
  necst/ctrl/antenna/__init__.py
  necst/ctrl/antenna/encoder.py
  necst/ctrl/antenna/horizontal_coord.py
  necst/ctrl/antenna/motor.py
  necst/ctrl/antenna/pid_controller.py
  necst/ctrl/antenna/weather_station.py
  necst/ctrl/calibrator/__init__.py
  necst/ctrl/calibrator/chopper.py
  necst/definitions.py
  necst/executors/antenna_dev.py
  necst/executors/attenuator.py
  necst/executors/clock.py
  necst/executors/record.py
  necst/executors/sg.py
  necst/executors/sis_bias.py
  necst/executors/thermometer.py
  necst/rx/__init__.py
  necst/rx/attenuator.py
  necst/rx/signal_generator.py
  necst/rx/sis_bias.py
  necst/rx/spectrometer.py
  necst/rx/thermometer.py
  necst/utils/ros_interface.py
  necst/utils/ros_thread.py
  package.xml
  setup.py
  tests/conftest.py
  tests/core/alert/test_antenna_drive_range.py
  tests/core/alert/test_antenna_speed.py
  tests/core/test_authority.py
  tests/core/test_commander.py
  tests/core/test_recorder.py
  tests/obs/test_rsky_obs.py
  tests/obs/test_skydip_obs.py
Labels: enhancement, release

#149 Fix missing return statement
  necst/core/commander.py
Labels: bug
