Repository necst-telescope/necst, pull requests merged in 2023-11, with the labels that each got.

#231 Implement the optical pointing
  Dockerfile
  bin/optical_pointing.py
  necst/core/commander.py
  necst/definitions.py
  necst/executors/ccd.py
  necst/procedures/observations/__init__.py
  necst/procedures/observations/optical_pointing.py
  necst/rx/__init__.py
  necst/rx/ccd.py
Labels: enhancement

#237 #233 edit bin comment
  bin/optical_pointing.py
  necst/rx/ccd.py
Labels: bug

#240 #236 opt bin
  bin/optical_pointing.py
Labels: bug

#243 #242 fix optical pointing
  necst/procedures/observations/optical_pointing.py
Labels: bug, enhancement

#241 #238 fix import of rx
  necst/rx/__init__.py
Labels: bug

#247 #246 fix topic name
  necst/rx/ccd.py
Labels: bug
