Repository necst-telescope/necst, pull requests merged in 2023-03, with the labels that each got.

#165 #162 hemtros
  necst/core/commander.py
  necst/definitions.py
  necst/executors/hemt_bias.py
  necst/procedures/observations/observation_base.py
  necst/procedures/observations/skydip.py
  necst/rx/__init__.py
  necst/rx/hemt_bias.py
Labels: enhancement

#161 Use NECLIB-defined observation spec parser
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  Dockerfile
  bin/otf.py
  bin/radio_pointing.py
  bin/rsky.py
  bin/skydip.py
  necst/__init__.py
  necst/core/commander.py
  necst/ctrl/antenna/horizontal_coord.py
  necst/definitions.py
  necst/executors/hemt_bias.py
  necst/procedures/observations/__init__.py
  necst/procedures/observations/file_based.py
  necst/procedures/observations/observation_base.py
  necst/procedures/observations/otf.py
  necst/procedures/observations/radio_pointing.py
  necst/procedures/observations/skydip.py
  necst/rx/__init__.py
  necst/rx/hemt_bias.py
  necst/rx/sis_bias.py
  tests/docs/test_build.py
  tests/procedures/test_rsky.py
  tests/procedures/test_skydip.py
  typings/necst_msgs/__init__.pyi
  typings/necst_msgs/msg/__init__.pyi
  typings/necst_msgs/srv/__init__.pyi
Labels: bug, enhancement

#171 Release v0.6.0
  Dockerfile
Labels: release

#167 #164 Add conditional branch in Spectrometer
  necst/rx/spectrometer.py
Labels: enhancement, invalid

#176 #175 hot moni
  bin/hot_monitor.py
  necst/procedures/observations/__init__.py
  necst/procedures/observations/hot_monitor.py
Labels: enhancement
