Repository necst-telescope/necst, pull requests merged in 2024-09, with the labels that each got.

#316 #315 ac240
  necst/rx/spectrometer.py
Labels: enhancement

#321 #320 modi config saving
  .github/workflows/test.yml
  necst/procedures/measurement/measurement_base.py
  necst/procedures/observation_base.py
Labels: bug

#323 #322 change file
  package.xml
  setup.py
Labels: release

#324 #322 sphinx
  .github/workflows/gh-pages.yml
  package.xml
  setup.py
Labels: release
